//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.PRODUCTOes = new HashSet<PRODUCTO>();
        }
    
        public int Suc_ID { get; set; }
        public int Prod_codigo { get; set; }
        public int Prov_cedula { get; set; }
        public string Descripcion { get; set; }
        public byte[] Foto_compra { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public System.DateTime Fecha_Real { get; set; }
        public decimal Monto { get; set; }
        public int Compra_ID { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTOes { get; set; }
    }
}
