//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRONOGRAMA
    {
        public int Suc_ID { get; set; }
        public int Trab_Cedula { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public System.DateTime Fecha_Final { get; set; }
        public int Horas_Laboradas { get; set; }
        public int Horas_Extra { get; set; }
    
        public virtual TRABAJADOR TRABAJADOR { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
