//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int Suc_ID { get; set; }
        public int Prod_Codigo { get; set; }
        public int Trab_Cedula { get; set; }
        public int Descuento { get; set; }
        public int Unid_vendidas { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Fact_numero { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
    }
}
